using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class MenuHUDScreen : ScreenBase
{
    [Header("Buttons")]
    [SerializeField] private Button pvpModeBtn;
    [SerializeField] private Button pvaiModeBtn;

    private PopupManager popupManager;
    private ScreenManager screenManager;

    private void OnEnable()
    {
        pvpModeBtn.onClick.AddListener(OnClick_pvpModeBtn);
    }

    private void OnDisable()
    {
        pvpModeBtn.onClick.RemoveListener(OnClick_pvpModeBtn);
    }

    private void OnClick_pvpModeBtn()
    {
        popupManager = popupManager == null ? InterfaceManager.Instance?.GetInterfaceInstance<PopupManager>() : popupManager;
        popupManager.ShowPopup(PopupType.PVPModePopup);

        Hide();
        // screenManager = screenManager == null ? InterfaceManager.Instance?.GetInterfaceInstance<ScreenManager>() : screenManager;
        // screenManager.HideScreen(ScreenType.MenuHUDScreen);
    }

}
